# 数据库的配置变量
HOSTNAME = '127.0.0.1'
POORT = '3306'
DATABASE = 'pl'
USERNAME = 'root'
PASSWORD = 'root'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME, PASSWORD, HOSTNAME, POORT, DATABASE)

SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True

SECRET_KEY = "wwww123123"

# 邮箱配置
# 项目用的是qq邮箱
MAIL_SERVER = "smtp.qq.com"
MAIL_PORT = 465
MAIL_USE_TLS =False
MAIL_USE_SSL = True
MAIL_DEBUG = True
MAIL_USERNAME = "2561837993@qq.com"
MAIL_PASSWORD = "txveybsinvrudhih"
MAIL_DEFAULT_SENDER = "2561837993@qq.com"
